### ISSUE TITLE
Rails server does not start when date_time_select_extension is enabled in Rails 5

### ISSUE THREAD

**Issue by AquisTech** [adzap/validates_timeliness#166]
Rails server does not start when date_time_select_extension is enabled in Rails 5

**Details:**
Ruby 2.4.0
Rails 5.2.0.beta2

**Error Trace:**
```
/home/AquisTech/projects/validates_timeliness/lib/validates_timeliness/extensions/date_time_select.rb:12:in `block in <module:DateTimeSelect>': undefined method `alias_method_chain' for ActionView::Helpers::Tags::DateSelect:Class (NoMethodError)
Did you mean?  alias_method
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/concern.rb:122:in `class_eval'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/concern.rb:122:in `append_features'
  from /home/AquisTech/projects/validates_timeliness/lib/validates_timeliness/extensions.rb:7:in `include'
  from /home/AquisTech/projects/validates_timeliness/lib/validates_timeliness/extensions.rb:7:in `enable_date_time_select_extension!'
  from /home/AquisTech/projects/expense_tracker/config/initializers/validates_timeliness.rb:15:in `block in <top (required)>'
  from /home/AquisTech/projects/validates_timeliness/lib/validates_timeliness.rb:54:in `setup'
  from /home/AquisTech/projects/expense_tracker/config/initializers/validates_timeliness.rb:1:in `<top (required)>'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/dependencies.rb:277:in `load'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/dependencies.rb:277:in `block in load'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/dependencies.rb:249:in `load_dependency'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/dependencies.rb:277:in `load'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/engine.rb:657:in `block in load_config_initializer'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/activesupport/lib/active_support/notifications.rb:170:in `instrument'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/engine.rb:656:in `load_config_initializer'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/engine.rb:614:in `block (2 levels) in <class:Engine>'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/engine.rb:613:in `each'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/engine.rb:613:in `block in <class:Engine>'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:32:in `instance_exec'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:32:in `run'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:61:in `block in run_initializers'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:228:in `block in tsort_each'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:431:in `each_strongly_connected_component_from'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:50:in `each'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:50:in `tsort_each_child'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:415:in `call'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:415:in `each_strongly_connected_component_from'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:349:in `block in each_strongly_connected_component'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `call'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:347:in `each_strongly_connected_component'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:226:in `tsort_each'
  from /home/AquisTech/.rvm/rubies/ruby-2.4.0/lib/ruby/2.4.0/tsort.rb:205:in `tsort_each'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/initializable.rb:60:in `run_initializers'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/application.rb:360:in `initialize!'
  from /home/AquisTech/projects/expense_tracker/config/environment.rb:5:in `<top (required)>'
  from config.ru:3:in `require_relative'
  from config.ru:3:in `block in <main>'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `instance_eval'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:55:in `initialize'
  from config.ru:in `new'
  from config.ru:in `<main>'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `eval'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:49:in `new_from_string'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/builder.rb:40:in `parse_file'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/server.rb:319:in `build_app_and_options_from_config'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/server.rb:219:in `app'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:27:in `app'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/rack-2.0.4/lib/rack/server.rb:354:in `wrapped_app'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:89:in `log_to_stdout'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:51:in `start'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:147:in `block in perform'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:142:in `tap'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands/server/server_command.rb:142:in `perform'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/command/base.rb:65:in `perform'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/command.rb:46:in `invoke'
  from /home/AquisTech/.rvm/gems/ruby-2.4.0/bundler/gems/rails-f7e3c686685f/railties/lib/rails/commands.rb:18:in `<top (required)>'
  from bin/rails:4:in `require'
  from bin/rails:4:in `<main>'
```

**Comment by AquisTech** [comment]
`alias_method_chain` is completely removed now in Rails 5.2.0 so need to make code compatible using Module.prepend

**Comment by AquisTech** [comment]
Changes done for fixing this issue.
PR #167 is raised for the fix.
@adzap Please review changes.
I am already using changes in my Rails 5.2.0 project.
