### ISSUE TITLE
Doesn't work with Ruby 3.0 / Rails 6.1 (PR attached)

### ISSUE THREAD

**Issue by tagliala** [adzap/validates_timeliness#193]
The failure I'm getting in the application is:

```rb
class MyModel
  validates :travel_on, presence: true, timeliness: { type: :date }, if: :business_trip?
end

my_model_instance.valid?
```

```
     ArgumentError:
       wrong number of arguments (given 3, expected 1..2)
     # ~/.rvm/gems/ruby-3.0.0-rc1/gems/validates_timeliness-5.0.0.beta2/lib/validates_timeliness/validator.rb:89:in `add_error'
     # ~/.rvm/gems/ruby-3.0.0-rc1/gems/validates_timeliness-5.0.0.beta2/lib/validates_timeliness/validator.rb:65:in `validate_each'
```

Specs don't even start with the current master branch here

```
$ rake
~/.rvm/rubies/ruby-2.7.2/bin/ruby -I~/.rvm/gems/ruby-2.7.2/gems/rspec-core-3.9.3/lib:~/.rvm/gems/ruby-2.7.2/gems/rspec-support-3.9.4/lib ~/.rvm/gems/ruby-2.7.2/gems/rspec-core-3.9.3/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error:
  def define_method_attribute(attr_name)
    generated_attribute_methods.module_eval("def #{attr_name}; @attributes['#{attr_name}']; end", __FILE__, __LINE__)
  end

ArgumentError:
  unknown keyword: :owner
# ./spec/support/test_model.rb:22:in `define_method_attribute'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:297:in `block (2 levels) in define_attribute_method'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:290:in `each'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:290:in `block in define_attribute_method'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:342:in `batch'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:289:in `define_attribute_method'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:255:in `block (2 levels) in define_attribute_methods'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:255:in `each'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:255:in `block in define_attribute_methods'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:345:in `batch'
# ~/.rvm/gems/ruby-2.7.2/gems/activemodel-6.1.0/lib/active_model/attribute_methods.rb:254:in `define_attribute_methods'
# ./spec/spec_helper.rb:53:in `<class:Person>'
# ./spec/spec_helper.rb:47:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00004 seconds (files took 0.53207 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00004 seconds (files took 0.53207 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
```

Will try to submit a PR

**Comment by tagliala** [comment]
Possible issue: the change of signature of `error.add` in ActiveModel

Ref:
- https://api.rubyonrails.org/v6.1.0/classes/ActiveModel/Errors.html#method-i-add
- https://api.rubyonrails.org/v6.0.0/classes/ActiveModel/Errors.html#method-i-add

Possible solution:


```rb
      record.errors.add(attr_name, message, **message_options)
```

Backward compatibility:

**Comment by adzap** [comment]
@tagliala fantastic! thanks for this. I think i will merge on a v6 branch for a beta release soon.

**Comment by tagliala** [comment]
@adzap welcome,

will wait for Travis to finish and then I will push another commit tomorrow to improve the Travis build, by testing against newer ruby versions as well as rails edge

PS: Travis is painfully slow in these days, and that change will make it even much slower :)

**Comment by pedrofurtado** [comment]
For anyone looking for support of Ruby 3 in 4.x versions of gem: https://github.com/adzap/validates_timeliness/pull/195
